package Vistas;

import com.formdev.flatlaf.intellijthemes.FlatSpacegrayIJTheme;
import java.awt.event.MouseEvent;
import java.beans.PropertyVetoException;
import javax.swing.JInternalFrame;

public class Escritorio extends javax.swing.JFrame {

  /**
   * Creates new form Escritorio
   */
  public Escritorio() {
    initComponents();
    //posiciono jFrame en el centro de la pantalla
    this.setLocationRelativeTo(null);
    // Agregamos al JMenu "menuSalir" un escuchador de eventos de mouse para
    // detectar cuando se haga click sobre él
    menuSalir.addMouseListener(new java.awt.event.MouseAdapter() {
      @Override
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        clickEnMenuSalir(evt);
      }
    });
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    escritorio = new javax.swing.JDesktopPane();
    jMenuBar1 = new javax.swing.JMenuBar();
    jMenu6 = new javax.swing.JMenu();
    menuVentaPasajes = new javax.swing.JMenuItem();
    menuConsultarPasajes = new javax.swing.JMenuItem();
    jMenu1 = new javax.swing.JMenu();
    menuCrearPasajero = new javax.swing.JMenuItem();
    jMenu2 = new javax.swing.JMenu();
    jMenuItem1 = new javax.swing.JMenuItem();
    jMenu3 = new javax.swing.JMenu();
    menuCrearRutas = new javax.swing.JMenuItem();
    jMenu4 = new javax.swing.JMenu();
    menuHorarios = new javax.swing.JMenuItem();
    jMenu5 = new javax.swing.JMenu();
    menuCrearCiudad = new javax.swing.JMenuItem();
    menuSalir = new javax.swing.JMenu();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setResizable(false);

    javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
    escritorio.setLayout(escritorioLayout);
    escritorioLayout.setHorizontalGroup(
      escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 800, Short.MAX_VALUE)
    );
    escritorioLayout.setVerticalGroup(
      escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 579, Short.MAX_VALUE)
    );

    jMenuBar1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

    jMenu6.setText("Pasajes");
    jMenu6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

    menuVentaPasajes.setText("Venta");
    menuVentaPasajes.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        menuVentaPasajesActionPerformed(evt);
      }
    });
    jMenu6.add(menuVentaPasajes);

    menuConsultarPasajes.setText("Consultar");
    menuConsultarPasajes.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        menuConsultarPasajesActionPerformed(evt);
      }
    });
    jMenu6.add(menuConsultarPasajes);

    jMenuBar1.add(jMenu6);

    jMenu1.setText("Pasajeros");
    jMenu1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

    menuCrearPasajero.setText("Crear/Editar");
    menuCrearPasajero.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        menuCrearPasajeroActionPerformed(evt);
      }
    });
    jMenu1.add(menuCrearPasajero);

    jMenuBar1.add(jMenu1);

    jMenu2.setText("Colectivos");
    jMenu2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
    jMenu2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jMenu2ActionPerformed(evt);
      }
    });

    jMenuItem1.setText("Crear/Editar");
    jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jMenuItem1ActionPerformed(evt);
      }
    });
    jMenu2.add(jMenuItem1);

    jMenuBar1.add(jMenu2);

    jMenu3.setText("Rutas");
    jMenu3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

    menuCrearRutas.setText("Crear/Editar");
    menuCrearRutas.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        menuCrearRutasActionPerformed(evt);
      }
    });
    jMenu3.add(menuCrearRutas);

    jMenuBar1.add(jMenu3);

    jMenu4.setText("Horarios");
    jMenu4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

    menuHorarios.setText("Crear/Editar");
    menuHorarios.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        menuHorariosActionPerformed(evt);
      }
    });
    jMenu4.add(menuHorarios);

    jMenuBar1.add(jMenu4);

    jMenu5.setText("Ciudades");
    jMenu5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

    menuCrearCiudad.setText("Crear/Editar");
    menuCrearCiudad.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        menuCrearCiudadActionPerformed(evt);
      }
    });
    jMenu5.add(menuCrearCiudad);

    jMenuBar1.add(jMenu5);

    menuSalir.setText("Salir");
    menuSalir.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
    jMenuBar1.add(menuSalir);

    setJMenuBar(jMenuBar1);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(escritorio)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(escritorio)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void menuCrearCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCrearCiudadActionPerformed
    // TODO add your handling code here:
    VistaCiudad vista = new VistaCiudad();
    cargarVista(vista);
  }//GEN-LAST:event_menuCrearCiudadActionPerformed

    private void menuCrearPasajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCrearPasajeroActionPerformed
    // TODO add your handling code here:
    VistaPasajero vista = new VistaPasajero();
    cargarVista(vista);
    }//GEN-LAST:event_menuCrearPasajeroActionPerformed

  private void menuCrearRutasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCrearRutasActionPerformed
    // TODO add your handling code here:
    VistaRuta vista = new VistaRuta();
    cargarVista(vista);
  }//GEN-LAST:event_menuCrearRutasActionPerformed

  private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jMenu2ActionPerformed

  private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
    // TODO add your handling code here:
    VistaColectivo vista = new VistaColectivo();
    cargarVista(vista);
  }//GEN-LAST:event_jMenuItem1ActionPerformed

  private void menuHorariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuHorariosActionPerformed
    // TODO add your handling code here:
    VistaHorarios vista = new VistaHorarios();
    cargarVista(vista);
  }//GEN-LAST:event_menuHorariosActionPerformed

  private void menuVentaPasajesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVentaPasajesActionPerformed
    // TODO add your handling code here:
    VistaVentaPasajes vista = new VistaVentaPasajes();
    cargarVista(vista);
  }//GEN-LAST:event_menuVentaPasajesActionPerformed

  private void menuConsultarPasajesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConsultarPasajesActionPerformed
    // TODO add your handling code here:
    VistaConsultarPasajes vista = new VistaConsultarPasajes();
    cargarVista(vista);
  }//GEN-LAST:event_menuConsultarPasajesActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(Escritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(Escritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(Escritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(Escritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    try {
      FlatSpacegrayIJTheme.setup();
    } catch (Exception ex) {
      System.err.println("Failed to initialize LaF");
    }

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new Escritorio().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JDesktopPane escritorio;
  private javax.swing.JMenu jMenu1;
  private javax.swing.JMenu jMenu2;
  private javax.swing.JMenu jMenu3;
  private javax.swing.JMenu jMenu4;
  private javax.swing.JMenu jMenu5;
  private javax.swing.JMenu jMenu6;
  private javax.swing.JMenuBar jMenuBar1;
  private javax.swing.JMenuItem jMenuItem1;
  private javax.swing.JMenuItem menuConsultarPasajes;
  private javax.swing.JMenuItem menuCrearCiudad;
  private javax.swing.JMenuItem menuCrearPasajero;
  private javax.swing.JMenuItem menuCrearRutas;
  private javax.swing.JMenuItem menuHorarios;
  private javax.swing.JMenu menuSalir;
  private javax.swing.JMenuItem menuVentaPasajes;
  // End of variables declaration//GEN-END:variables

  /**
   * Carga y muestra un JInternalFrame en el contenedor principal de la
   * aplicación. Si el JInternalFrame ya está visible, se trae al frente.
   *
   * @param vista El JInternalFrame que se cargará y mostrará.
   */
  private void cargarVista(JInternalFrame vista) {
    escritorio.removeAll();
    escritorio.repaint();
    vista.moveToFront();
    vista.setVisible(true);
    escritorio.add(vista);

    try {
      vista.setSelected(true);
    } catch (PropertyVetoException ex) {
      System.out.println(ex);
    }
  }

  /**
   * Maneja el evento de clic en el menú "Salir". Cierra la aplicación cuando el
   * menú "Salir" es clickeado.
   *
   * @param evt El evento de clic del ratón.
   */
  private void clickEnMenuSalir(java.awt.event.MouseEvent evt) {
    if (evt.getButton() == MouseEvent.BUTTON1) {
      System.exit(0);
    }
  }
}
